import type {
  CarEvent,
  CarShop,
  Club,
  ClubMember,
  Community,
  CommunityZone,
  Submission,
} from "@/lib/types";

const now = new Date();
const iso = (offsetDays: number, hour = 10, minute = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const mockShops: CarShop[] = [
  {
    id: "kmc-performance",
    name: "KMC Performance",
    category: "turbo",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    address: "Industriestraße 12",
    lat: 49.443,
    lng: 7.769,
    description:
      "Performance upgrades, turbo builds, ECU tuning, exhaust systems and more. Passion for performance.",
    instagram: "@kmcperformance",
    website: "https://example.com/kmc",
    verified: true,
    featured: true,
    services: ["Turbo", "ECU Tuning", "Exhaust", "Intake", "Brakes"],
    brandsSupported: ["VAG", "BMW", "Subaru"],
    rating: 4.9,
    reviewCount: 128,
    sponsorLevel: "featured",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "turbo-zone",
    name: "Turbo Zone",
    category: "turbo",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    lat: 49.4375,
    lng: 7.602,
    description: "Turbo specialists for street and track builds.",
    instagram: "@turbozone",
    verified: true,
    featured: false,
    services: ["Turbo", "Dyno", "Fabrication"],
    rating: 4.6,
    reviewCount: 64,
    sponsorLevel: "verified",
    createdAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: "wheel-empire",
    name: "Wheel Empire",
    category: "wheels",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    lat: 49.4385,
    lng: 7.735,
    description: "Custom wheels, fitment, and tire packages for every build.",
    instagram: "@wheelempire",
    verified: false,
    featured: true,
    services: ["Wheels", "Tires", "Fitment", "Mount & Balance"],
    rating: 4.8,
    reviewCount: 92,
    sponsorLevel: "verified",
  },
  {
    id: "detailing-kings",
    name: "Detailing Kings",
    category: "detailing",
    status: "approved",
    city: "Mannheim",
    country: "Germany",
    lat: 49.4875,
    lng: 8.466,
    description: "Premium detailing, ceramic coating, and paint correction.",
    verified: true,
    services: ["Detail", "Ceramic", "PPF"],
    rating: 4.7,
    reviewCount: 55,
  },
  {
    id: "royal-wraps",
    name: "Royal Wraps",
    category: "wrap_tint",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    lat: 49.4418,
    lng: 7.758,
    description: "Premium vinyl wraps, PPF, and ceramic tint for enthusiasts.",
    instagram: "@royalwraps",
    verified: true,
    featured: true,
    services: ["Full Wrap", "PPF", "Tint", "Color Change"],
    rating: 4.7,
    reviewCount: 81,
    sponsorLevel: "featured",
  },
  {
    id: "b58-garage",
    name: "B58 Garage",
    category: "tuning",
    status: "approved",
    city: "Landstuhl",
    country: "Germany",
    lat: 49.428,
    lng: 7.568,
    description:
      "BMW specialist — B58, S58, and N55 builds, tuning, and maintenance for KMC enthusiasts.",
    instagram: "@b58garage",
    website: "https://example.com/b58garage",
    verified: true,
    featured: true,
    services: ["B58 Tuning", "Maintenance", "Exhaust", "Intake"],
    brandsSupported: ["BMW"],
    rating: 4.8,
    reviewCount: 76,
    sponsorLevel: "verified",
    createdAt: "2025-03-01T10:00:00.000Z",
  },
];

export const mockEvents: CarEvent[] = [
  {
    id: "cars-coffee-kl",
    title: "Cars & Coffee Kaiserslautern",
    type: "Meet",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description:
      "Weekly morning meet for all makes and models. Coffee, cars, and community.",
    startTime: iso(14, 9, 0),
    endTime: iso(14, 12, 0),
    organizerName: "KL Car Culture",
    organizerInstagram: "@klcarculture",
    lat: 49.442,
    lng: 7.752,
    verified: true,
    featured: true,
    interestedCount: 248,
  },
  {
    id: "midnight-cruise",
    title: "Midnight Cruise",
    type: "Cruise",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    description: "Late-night scenic cruise through the Pfalz region.",
    startTime: iso(20, 22, 0),
    lat: 49.436,
    lng: 7.598,
    verified: true,
    interestedCount: 412,
  },
  {
    id: "japfest",
    title: "JapFest Germany",
    type: "Festival",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    description: "Annual JDM and Japanese car culture festival.",
    startTime: iso(42, 10, 0),
    endTime: iso(42, 18, 0),
    lat: 50.1109,
    lng: 8.6821,
    verified: true,
    featured: true,
    interestedCount: 1893,
  },
  {
    id: "nurburgring-weekend-run",
    title: "Nürburgring Weekend Run",
    type: "Track",
    status: "approved",
    city: "Nürburg",
    country: "Germany",
    description:
      "Convoy to the Nürburgring with timed tourist drives and meet at the paddock.",
    startTime: iso(28, 8, 0),
    endTime: iso(28, 18, 0),
    organizerName: "Nürburgring Weekend Crew",
    lat: 50.334,
    lng: 6.942,
    verified: true,
    featured: true,
    interestedCount: 624,
    createdAt: "2025-04-10T10:00:00.000Z",
  },
  {
    id: "kmc-sunday-meet",
    title: "KMC Sunday Meet",
    type: "Meet",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description:
      "Weekly Sunday afternoon meet — all makes welcome, food trucks and photo spots.",
    startTime: iso(7, 14, 0),
    endTime: iso(7, 17, 0),
    organizerName: "KMC Street Society",
    lat: 49.439,
    lng: 7.761,
    verified: true,
    featured: false,
    interestedCount: 186,
    createdAt: "2025-04-15T10:00:00.000Z",
  },
];

export const mockCommunities: Community[] = [
  {
    id: "bavarian-crew",
    name: "Bavarian Crew",
    type: "Euro Club",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Euro builds, meets & cruises",
    instagram: "@bavariancrew",
    memberCount: 2400,
    verified: true,
    featured: true,
  },
  {
    id: "jdm-kl",
    name: "JDM Kaiserslautern",
    type: "JDM Club",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "JDM culture & street meets",
    instagram: "@jdmkl",
    memberCount: 1800,
    verified: true,
  },
  {
    id: "muscle-de",
    name: "Muscle Cars Germany",
    type: "Muscle Club",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    description: "American muscle community",
    memberCount: 3100,
    verified: true,
  },
  {
    id: "kmc-street",
    name: "KMC Street Society",
    type: "Street Crew",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    description: "Local street & track crew",
    memberCount: 920,
    verified: false,
  },
];

export const mockCommunityZones: CommunityZone[] = [
  {
    id: "bavarian-zone",
    name: "Bavarian Crew",
    communityId: "bavarian-crew",
    type: "Club Area",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    centerLat: 49.44,
    centerLng: 7.77,
    radiusMeters: 800,
    description: "Primary meet zone for Bavarian Crew gatherings.",
    verified: true,
    confidenceScore: 0.92,
  },
  {
    id: "jdm-zone",
    name: "JDM Zone",
    communityId: "jdm-kl",
    type: "Club Area",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    centerLat: 49.4355,
    centerLng: 7.762,
    radiusMeters: 650,
    description: "Known JDM hangout and photo spot.",
    verified: true,
    confidenceScore: 0.88,
  },
  {
    id: "muscle-area",
    name: "Muscle Area",
    communityId: "muscle-de",
    type: "Club Area",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    centerLat: 50.108,
    centerLng: 8.675,
    radiusMeters: 900,
    description: "Muscle car meet corridor.",
    verified: true,
    confidenceScore: 0.85,
  },
  {
    id: "kmc-zone",
    name: "KMC Street Society Area",
    communityId: "kmc-street",
    type: "Club Area",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    centerLat: 49.434,
    centerLng: 7.608,
    radiusMeters: 700,
    description: "Ramstein / KMC street meet and cruise staging area.",
    verified: false,
    confidenceScore: 0.8,
  },
];

export const mockClubs: Club[] = [
  {
    id: "bavarian-crew",
    name: "Bavarian Crew",
    slug: "bavarian-crew",
    type: "BMW / German cars",
    category: "BMW",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    area: "KMC",
    description:
      "Euro builds, weekend cruises, and BMW-focused meets around Kaiserslautern and the KMC area.",
    instagram: "https://instagram.com/example",
    website: "https://example.com/bavarian-crew",
    memberCount: 2400,
    verified: true,
    featured: true,
    tags: ["BMW", "Euro", "Mixed"],
    lat: 49.441,
    lng: 7.755,
  },
  {
    id: "jdm-kl",
    name: "JDM Kaiserslautern",
    slug: "jdm-kaiserslautern",
    type: "JDM",
    category: "JDM",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    area: "KMC",
    description:
      "JDM culture, street meets, and build showcases for Japanese performance enthusiasts.",
    instagram: "https://instagram.com/example",
    tiktok: "https://tiktok.com/@example",
    memberCount: 1800,
    verified: true,
    featured: true,
    tags: ["JDM", "Drift"],
    lat: 49.439,
    lng: 7.748,
  },
  {
    id: "muscle-de",
    name: "Muscle Cars Germany",
    slug: "muscle-cars-germany",
    type: "American muscle",
    category: "Muscle",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    area: "Ramstein",
    description:
      "American muscle community with cruises between Ramstein, Frankfurt, and surrounding bases.",
    instagram: "https://instagram.com/example",
    youtube: "https://youtube.com/@example",
    memberCount: 3100,
    verified: true,
    featured: false,
    tags: ["Muscle", "Mixed"],
    lat: 50.108,
    lng: 8.68,
  },
  {
    id: "kmc-street",
    name: "KMC Street Society",
    slug: "kmc-street-society",
    type: "Mixed enthusiast group",
    category: "Mixed",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    area: "KMC",
    description:
      "Open-minded street and track crew welcoming all builds in the KMC area.",
    instagram: "https://instagram.com/example",
    memberCount: 920,
    verified: false,
    featured: false,
    tags: ["Mixed"],
    lat: 49.437,
    lng: 7.605,
  },
  {
    id: "nurburgring-weekend",
    name: "Nürburgring Weekend Crew",
    slug: "nurburgring-weekend-crew",
    type: "Track / cruise",
    category: "Mixed",
    status: "approved",
    city: "Nürburg",
    country: "Germany",
    area: "Nürburgring",
    description:
      "Track days, ring taxis, and weekend convoys for enthusiasts visiting the Nürburgring.",
    instagram: "https://instagram.com/example",
    website: "https://example.com/nring-crew",
    memberCount: 1560,
    verified: true,
    featured: true,
    tags: ["Mixed", "Classic"],
    lat: 50.3356,
    lng: 6.9475,
  },
];

export const mockClubMembers: ClubMember[] = [
  {
    id: "member-alex",
    clubId: "bavarian-crew",
    displayName: "Alex",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    area: "KMC",
    carMake: "BMW",
    carModel: "M340i",
    carYear: "2021",
    carName: "Daily B58",
    buildSummary: "B58, Stage 2, Exhaust",
    buildTags: ["B58", "Stage 2", "Exhaust"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    featured: true,
    lat: 49.4425,
    lng: 7.756,
  },
  {
    id: "member-marco",
    clubId: "bavarian-crew",
    displayName: "Marco",
    nickname: "M3 Marco",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    carMake: "BMW",
    carModel: "M3 F80",
    carYear: "2018",
    buildSummary: "M Performance, Wheels, Track Setup",
    buildTags: ["M Performance", "Wheels", "Track Setup"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    lat: 49.4408,
    lng: 7.751,
  },
  {
    id: "member-boris",
    clubId: "bavarian-crew",
    displayName: "Boris",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    carMake: "BMW",
    carModel: "X5 G05",
    carYear: "2020",
    buildSummary: "B58, Intake, SST Controller",
    buildTags: ["B58", "Intake", "SST Controller"],
    instagram: "https://instagram.com/example",
    verifiedByClub: false,
    lat: 49.438,
    lng: 7.61,
  },
  {
    id: "member-ken",
    clubId: "jdm-kl",
    displayName: "Ken",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    carMake: "Toyota",
    carModel: "Supra MK5",
    carYear: "2022",
    buildSummary: "B58, Downpipe, Tune",
    buildTags: ["B58", "Downpipe", "Tune"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    featured: true,
    lat: 49.4395,
    lng: 7.746,
  },
  {
    id: "member-lena",
    clubId: "jdm-kl",
    displayName: "Lena",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    carMake: "Nissan",
    carModel: "350Z",
    carYear: "2008",
    buildSummary: "Drift, Wheels, Exhaust",
    buildTags: ["Drift", "Wheels", "Exhaust"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    lat: 49.4378,
    lng: 7.744,
  },
  {
    id: "member-sam",
    clubId: "jdm-kl",
    displayName: "Sam",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    carMake: "Honda",
    carModel: "Civic Type R",
    carYear: "2019",
    carName: "FK8",
    buildSummary: "FK8, Track, Intake",
    buildTags: ["FK8", "Track", "Intake"],
    instagram: "https://instagram.com/example",
    verifiedByClub: false,
    lat: 49.4362,
    lng: 7.749,
  },
  {
    id: "member-chris",
    clubId: "muscle-de",
    displayName: "Chris",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    carMake: "Ford",
    carModel: "Mustang GT",
    carYear: "2019",
    buildSummary: "V8, Exhaust, Wheels",
    buildTags: ["V8", "Exhaust", "Wheels"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    featured: true,
    lat: 49.435,
    lng: 7.601,
  },
  {
    id: "member-daniel",
    clubId: "muscle-de",
    displayName: "Daniel",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    carMake: "Dodge",
    carModel: "Charger",
    carYear: "2017",
    buildSummary: "HEMI, Widebody, Tint",
    buildTags: ["HEMI", "Widebody", "Tint"],
    instagram: "https://instagram.com/example",
    verifiedByClub: true,
    lat: 50.112,
    lng: 8.685,
  },
];

export const mockSubmissionsSeed: Submission[] = [
  {
    id: "sub-1",
    type: "shop",
    status: "pending",
    name: "Turbo Zone",
    category: "turbo",
    city: "Ramstein",
    country: "Germany",
    description: "New turbo shop submission",
    createdAt: "2025-05-01T12:00:00.000Z",
  },
  {
    id: "sub-2",
    type: "event",
    status: "pending",
    name: "Midnight Cruise",
    category: "Cruise",
    city: "Ramstein",
    country: "Germany",
    description: "Recurring midnight cruise event",
    createdAt: "2025-05-02T18:00:00.000Z",
  },
  {
    id: "sub-3",
    type: "community",
    status: "pending",
    name: "JDM Kaiserslautern",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Community profile update",
    createdAt: "2025-05-03T09:00:00.000Z",
  },
  {
    id: "sub-4",
    type: "member",
    status: "pending",
    name: "Max M340i",
    clubName: "Bavarian Crew",
    city: "Kaiserslautern",
    country: "Germany",
    description: "New member build submission",
    carMake: "BMW",
    carModel: "M340i",
    carYear: "2022",
    buildTags: ["stage 1", "exhaust"],
    instagram: "https://instagram.com/example",
    permissionConfirmed: true,
    createdAt: "2025-05-04T14:00:00.000Z",
  },
  {
    id: "sub-5",
    type: "correction",
    status: "approved",
    name: "B58 Garage",
    targetType: "shop",
    targetName: "B58 Garage",
    correctionDetails: "Updated opening hours",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Updated opening hours",
    reviewedAt: "2025-05-05T10:00:00.000Z",
    createdAt: "2025-05-04T16:00:00.000Z",
    updatedAt: "2025-05-05T10:00:00.000Z",
  },
  {
    id: "sub-6",
    type: "club",
    status: "rejected",
    name: "Spam Crew",
    city: "Berlin",
    country: "Germany",
    description: "Duplicate club listing",
    reviewNote: "Duplicate of existing club profile.",
    reviewedAt: "2025-05-03T11:00:00.000Z",
    createdAt: "2025-05-02T08:00:00.000Z",
    updatedAt: "2025-05-03T11:00:00.000Z",
  },
  {
    id: "sub-7",
    type: "shop",
    status: "needs_changes",
    name: "Wrap Lab",
    category: "wrap",
    city: "Stuttgart",
    country: "Germany",
    description: "Wrap shop near city center",
    reviewNote: "Please add street address and Instagram link.",
    reviewedAt: "2025-05-06T09:00:00.000Z",
    createdAt: "2025-05-05T12:00:00.000Z",
    updatedAt: "2025-05-06T09:00:00.000Z",
  },
];
