import type {
  CarEvent,
  CarShop,
  Community,
  CommunityZone,
  Submission,
} from "@/lib/types";

const now = new Date();
const iso = (offsetDays: number, hour = 10, minute = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const mockShops: CarShop[] = [
  {
    id: "kmc-performance",
    name: "KMC Performance",
    category: "turbo",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    address: "Industriestraße 12",
    lat: 49.443,
    lng: 7.769,
    description:
      "Performance upgrades, turbo builds, ECU tuning, exhaust systems and more. Passion for performance.",
    instagram: "@kmcperformance",
    website: "https://example.com/kmc",
    verified: true,
    featured: true,
    services: ["Turbo", "ECU Tuning", "Exhaust", "Intake", "Brakes"],
    brandsSupported: ["VAG", "BMW", "Subaru"],
    rating: 4.9,
    reviewCount: 128,
    sponsorLevel: "featured",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "turbo-zone",
    name: "Turbo Zone",
    category: "turbo",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    description: "Turbo specialists for street and track builds.",
    instagram: "@turbozone",
    verified: true,
    featured: false,
    services: ["Turbo", "Dyno", "Fabrication"],
    rating: 4.6,
    reviewCount: 64,
    sponsorLevel: "verified",
    createdAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: "wheel-empire",
    name: "Wheel Empire",
    category: "wheels",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Custom wheels, fitment, and tire packages for every build.",
    instagram: "@wheelempire",
    verified: false,
    featured: true,
    services: ["Wheels", "Tires", "Fitment", "Mount & Balance"],
    rating: 4.8,
    reviewCount: 92,
    sponsorLevel: "verified",
  },
  {
    id: "detailing-kings",
    name: "Detailing Kings",
    category: "detailing",
    status: "approved",
    city: "Mannheim",
    country: "Germany",
    description: "Premium detailing, ceramic coating, and paint correction.",
    verified: true,
    services: ["Detail", "Ceramic", "PPF"],
    rating: 4.7,
    reviewCount: 55,
  },
  {
    id: "royal-wraps",
    name: "Royal Wraps",
    category: "wrap_tint",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Premium vinyl wraps, PPF, and ceramic tint for enthusiasts.",
    instagram: "@royalwraps",
    verified: true,
    featured: true,
    services: ["Full Wrap", "PPF", "Tint", "Color Change"],
    rating: 4.7,
    reviewCount: 81,
    sponsorLevel: "featured",
  },
];

export const mockEvents: CarEvent[] = [
  {
    id: "cars-coffee-kl",
    title: "Cars & Coffee Kaiserslautern",
    type: "Meet",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description:
      "Weekly morning meet for all makes and models. Coffee, cars, and community.",
    startTime: iso(14, 9, 0),
    endTime: iso(14, 12, 0),
    organizerName: "KL Car Culture",
    organizerInstagram: "@klcarculture",
    verified: true,
    featured: true,
    interestedCount: 248,
  },
  {
    id: "midnight-cruise",
    title: "Midnight Cruise",
    type: "Cruise",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    description: "Late-night scenic cruise through the Pfalz region.",
    startTime: iso(20, 22, 0),
    verified: true,
    interestedCount: 412,
  },
  {
    id: "japfest",
    title: "JapFest Germany",
    type: "Festival",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    description: "Annual JDM and Japanese car culture festival.",
    startTime: iso(42, 10, 0),
    endTime: iso(42, 18, 0),
    verified: true,
    featured: true,
    interestedCount: 1893,
  },
];

export const mockCommunities: Community[] = [
  {
    id: "bavarian-crew",
    name: "Bavarian Crew",
    type: "Euro Club",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Euro builds, meets & cruises",
    instagram: "@bavariancrew",
    memberCount: 2400,
    verified: true,
    featured: true,
  },
  {
    id: "jdm-kl",
    name: "JDM Kaiserslautern",
    type: "JDM Club",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "JDM culture & street meets",
    instagram: "@jdmkl",
    memberCount: 1800,
    verified: true,
  },
  {
    id: "muscle-de",
    name: "Muscle Cars Germany",
    type: "Muscle Club",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    description: "American muscle community",
    memberCount: 3100,
    verified: true,
  },
  {
    id: "kmc-street",
    name: "KMC Street Society",
    type: "Street Crew",
    status: "approved",
    city: "Ramstein",
    country: "Germany",
    description: "Local street & track crew",
    memberCount: 920,
    verified: false,
  },
];

export const mockCommunityZones: CommunityZone[] = [
  {
    id: "bavarian-zone",
    name: "Bavarian Crew",
    communityId: "bavarian-crew",
    type: "Club Area",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    centerLat: 49.44,
    centerLng: 7.77,
    radiusMeters: 800,
    description: "Primary meet zone for Bavarian Crew gatherings.",
    verified: true,
    confidenceScore: 0.92,
  },
  {
    id: "jdm-zone",
    name: "JDM Zone",
    communityId: "jdm-kl",
    type: "Club Area",
    status: "approved",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Known JDM hangout and photo spot.",
    verified: true,
    confidenceScore: 0.88,
  },
  {
    id: "muscle-area",
    name: "Muscle Area",
    communityId: "muscle-de",
    type: "Club Area",
    status: "approved",
    city: "Frankfurt",
    country: "Germany",
    description: "Muscle car meet corridor.",
    verified: true,
    confidenceScore: 0.85,
  },
];

export const mockSubmissionsSeed: Submission[] = [
  {
    id: "sub-1",
    type: "shop",
    status: "pending",
    name: "Turbo Zone",
    category: "turbo",
    city: "Ramstein",
    country: "Germany",
    description: "New turbo shop submission",
    createdAt: "2025-05-01T12:00:00.000Z",
  },
  {
    id: "sub-2",
    type: "event",
    status: "pending",
    name: "Midnight Cruise",
    category: "Cruise",
    city: "Ramstein",
    country: "Germany",
    description: "Recurring midnight cruise event",
    createdAt: "2025-05-02T18:00:00.000Z",
  },
  {
    id: "sub-3",
    type: "community",
    status: "pending",
    name: "JDM Kaiserslautern",
    city: "Kaiserslautern",
    country: "Germany",
    description: "Community profile update",
    createdAt: "2025-05-03T09:00:00.000Z",
  },
];
